# Simply creates a release-latest.tar.gz from recent master branch.
name: Release tarball

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create tarball
        run: |
          REPO="${GITHUB_REPOSITORY##*/}"
          git archive \
            --format=tar.gz \
            --prefix="${REPO}/" \
            -o "release-latest.tar.gz" \
            master

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: master 
          name: release-latest
          files: "*.tar.gz"

